-- Equipes de manutenção
CREATE TABLE EQUIPE_MANUTENCAO (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_EQUIPE   VARCHAR2(100)  NOT NULL,
    RESPONSAVEL   VARCHAR2(100)  NOT NULL
);

-- Trechos de rodovia monitorados
CREATE TABLE TRECHO_RODOVIA (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_RODOVIA      VARCHAR2(50)   NOT NULL,
    KM_INICIAL        NUMBER(10,2)   NOT NULL,
    KM_FINAL          NUMBER(10,2)   NOT NULL,
    NIVEL_VEGETACAO   NUMBER(10,2)   NOT NULL,
    TIPO_TERRENO      VARCHAR2(20)   NOT NULL,
    MONITORADO_IOT    NUMBER(1)      DEFAULT 0 NOT NULL
);

-- Histórico de intervenções operacionais executadas em cada trecho
CREATE TABLE INTERVENCAO_OPERACIONAL (
    ID                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TRECHO          NUMBER         NOT NULL,
    TIPO_INTERVENCAO   VARCHAR2(50)   NOT NULL,
    DATA_EXECUCAO      TIMESTAMP      NOT NULL,
    OBSERVACAO         VARCHAR2(200),
    CONSTRAINT FK_INTERVENCAO_TRECHO
        FOREIGN KEY (ID_TRECHO) REFERENCES TRECHO_RODOVIA (ID)
);

-- Histórico dos relatórios de priorização gerados
CREATE TABLE RELATORIO_PRIORIDADE (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_GERACAO    TIMESTAMP      NOT NULL,
    QT_URGENTE      NUMBER(5)      DEFAULT 0 NOT NULL,
    QT_CRITICO      NUMBER(5)      DEFAULT 0 NOT NULL,
    QT_ATENCAO      NUMBER(5)      DEFAULT 0 NOT NULL,
    QT_NORMAL       NUMBER(5)      DEFAULT 0 NOT NULL,
    RESUMO          VARCHAR2(500)
);
