INSERT INTO EQUIPE_MANUTENCAO (NOME_EQUIPE, RESPONSAVEL)
VALUES ('Equipe Sul', 'Carlos Silva');

INSERT INTO EQUIPE_MANUTENCAO (NOME_EQUIPE, RESPONSAVEL)
VALUES ('Equipe Norte', 'Ana Pereira');

INSERT INTO TRECHO_RODOVIA (NOME_RODOVIA, KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_TERRENO, MONITORADO_IOT)
VALUES ('BR-116', 10, 15, 12, 'SECO', 1);

INSERT INTO TRECHO_RODOVIA (NOME_RODOVIA, KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_TERRENO, MONITORADO_IOT)
VALUES ('BR-101', 20, 25, 28, 'UMIDO', 0);

INSERT INTO TRECHO_RODOVIA (NOME_RODOVIA, KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO, TIPO_TERRENO, MONITORADO_IOT)
VALUES ('BR-050', 5, 10, 48, 'UMIDO', 1);

COMMIT;
